version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: services-test-container
    build: ./services-test  # Match folder name correctly
    env_file: .env
    ports:
      - "8090:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  frontend:
    container_name: ui-test-container

    build: ./ui-test
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres-data:


